### ISSUE TITLE
Improve documentatation about API token generation

### ISSUE THREAD

**Issue by Jefrimm** [bluecurrent/ha-bluecurrent#29]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/bluecurrent/ha-bluecurrent/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

The Prerequisites section in the README.md does not help me to generate an API token. After logging in and going to settings, the 'enable developer mode' option is missing

### Describe the solution you'd like

Improve the Prerequisites section in the README.md

### Describe alternatives you've considered

I have not considered alternatives

### Additional context

I don't have additional context

**Comment by x6ryK3Bomur6hm** [comment]
Seconding this request. There is no "developer mode" option in the settings of the my.bluecurrent website. Where can we find the API token?

**Comment by Floris272** [comment]
Hi guys,

Sorry for the late reply. The developer mode will be added soon, for now you can email samen@bluecurrent.nl and ask for an Home assistant api token.

I will update the readme later today.

**Comment by Floris272** [comment]
developer mode / the advanced tab has been added to the website and the readme has been updated.
