### ISSUE TITLE
Request limit reached

### ISSUE THREAD

**Issue by abeltman** [bluecurrent/ha-bluecurrent#49]
## System Information

version | core-2023.9.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.5
os_name | Linux
os_version | 6.1.45
arch | x86_64
timezone | Europe/Amsterdam
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 5000
Installed Version | 1.33.0
Stage | running
Available Repositories | 1304
Downloaded Repositories | 29

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 10.5
-- | --
update_channel | stable
supervisor_version | supervisor-2023.09.2
agent_version | 1.5.1
docker_version | 23.0.6
disk_total | 62.3 GB
disk_used | 32.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.6.0), Samba share (10.0.2), Terminal & SSH (9.7.1), Home Assistant Google Drive Backup (0.111.1), Grafana (9.0.3), InfluxDB (4.7.0), Mosquitto broker (6.3.1), Duck DNS (1.15.0), SQLite Web (3.9.3), MariaDB (2.6.1), Portainer (2.19.1), ESPHome (2023.9.1), Volvo2Mqtt (1.8.7)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 19
views | 7
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29 September 2023 at 13:25
-- | --
current_recorder_run | 2 October 2023 at 21:27
estimated_db_size | 661.98 MiB
database_engine | mysql
database_version | 10.6.12

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/bluecurrent/ha-bluecurrent/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

After latest reboot I noticed that the Blue Current integration was no longer working. I have removed the integration from Devices & Services and have tried to reinstall the integration but unfortunately I now get the following error when I enter the API code:

Request limit reached

I have also used the 

I'm unable to reinstall the integration.

### Reproduction steps

1. Reboot HA - Blue Current integration failed
2. Redownload HACS integration - no result
3. Remove integration from Devices & Services and reinstall using API - unable to add with error Request limit reached
...

### Debug logs

```text
No details showing in logs
```

**Comment by Floris272** [comment]
Thank you for creating an issue! There was a bug on the server, It should be fixed now.
